[config]
schemaVersion = "0.0.1"

[package]
namespace = "DiFFoZ"
name = "BepInEx_MonoMod_Debug_Patcher"
versionNumber = "0.0.0"
description = "Makes exception easier to debug"
websiteUrl = "https://thunderstore.io"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""


[publish]
repository = "https://thunderstore.io"
communities = [ "lethal-company", "repo"]
[publish.categories]
lethal-company = [ "performance" ]
repo = [ "misc" ]